_wandb:
    value:
        cli_version: 0.19.4
        m:
            - "1": iter
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": iter_time
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": learning_rate
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 6
                - 9
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 103
                - 106
            "2":
                - 1
                - 5
                - 6
                - 9
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 103
                - 106
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.10.12
            "5": 0.19.4
            "6": 4.48.1
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
